on right click on llama:
    make player execute "/dupe"

command /dupe:
	description: Dupes
	cooldown: 0.001 minutes
	cooldown message: /dupe is on cooldown
	cooldown bypass: dupe.nocooldown
	
	trigger:
		if the player doesn't have enough space for 1 feather:
			send "not enough inventory space!"
			cancel command cooldown
		else:
			set {_i} to item amount of player's held item
			give {_i} of player's held item to player
